### PR TITLE
fix: better non-existing column errors (fixes #103)

### LINKED ISSUE #103: Better error messages when user refers to non-existing columns
Currently, if you make a typo in a reference to a column in the Mark properties:

```
<vgg-map v-slot="{ row }">
        <vgg-point :x="row.this_column_doesnt_exist" :y="row.resale_price"/>
      </vgg-map>
```
You get this error:
image

If you make the same typo in a scale definition:
```
<vgg-scales :scales="{ myScale: { domain: 'this_column_doesnt_exist' } }"/>
```
We get:
image

This is one of the key hurdles that new users struggle with. Can we create more informative error message that help troubleshoot where/what the mistake in the `<template>` is?

### PR DESCRIPTION
**Pull request by luucvanderzee**

### CODE REVIEW

File: src/classes/Data/DataContainer.js [hunk 1]
```diff
@@ -144,20 +144,47 @@ export default class {
     return this._dataset[colName]
   }
 
+  // forEachRow (fn) {
```
Comment (atepoorthuis) [inline src/classes/Data/DataContainer.js]: Is there a reason to keep this commented-out block around?

Comment (luucvanderzee) [reply src/classes/Data/DataContainer.js]: Well, rn the new Proxy implementation performs slightly worse than the original one... which is odd, imo. I initially thought that the `new Proxy` steps took a long time, and that performance would improve for larger datasets- but this turned out not to be the case either. According to this article, `Object.defineProperty` should be fastest, followed by proxy. But I am really not able to reproduce these results... do you know what I might be doing wrong?
